"""
translate.py — translate EN markdown chapters to zh-CN using the Claude API.

Diff-based: only translates chapters whose EN source has changed since the last
run (tracked via a content hash cache). Auto-generated appendices (A, C, D) are
skipped — those are already produced bilingually by gen_docs.py.

Usage:
  ANTHROPIC_API_KEY=sk-... python translate.py \\
      --src ../src/en --dst ../src/zh \\
      --model claude-opus-4-6 \\
      --glossary ../src/zh/appendix-c-glossary.md
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path

try:
    import anthropic
except ImportError:
    print("ERROR: pip install anthropic", file=sys.stderr)
    sys.exit(1)


CACHE_FILE = ".translate-cache/hashes.json"

# Files generated by gen_docs.py — do not translate.
SKIP = {"appendix-a-menus.md", "appendix-c-glossary.md", "appendix-d-changelog.md"}


SYSTEM_PROMPT = """You are a professional technical translator specialising in automotive ECU \
calibration software. You translate English documentation into Simplified Chinese (zh-CN).

RULES:
1. Output ONLY the translated Markdown — no preamble, no explanation, no code fences around the whole document.
2. Preserve ALL Markdown structure exactly: headings, lists, tables, links, images, admonitions, code blocks.
3. Do NOT translate: code, file paths, command names, file extensions, URLs, environment variables, \
class names, function names, or anything inside backticks or fenced code blocks.
4. Do NOT translate the chapter's H1 title if it appears to already match a Chinese convention; \
otherwise translate it naturally.
5. Use the provided glossary to keep UI terminology consistent with the application's actual zh-CN strings.
6. Preserve all MkDocs Material admonition syntax (`!!! note`, `!!! tip`, etc.) — translate the body, \
not the keyword.
7. Keep tone professional, concise and technical. This is a user manual for engineers.
"""


def load_cache(root: Path) -> dict[str, str]:
    p = root / CACHE_FILE
    if p.exists():
        return json.loads(p.read_text(encoding="utf-8"))
    return {}


def save_cache(root: Path, cache: dict[str, str]) -> None:
    p = root / CACHE_FILE
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(cache, indent=2, ensure_ascii=False), encoding="utf-8")


def file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_glossary(glossary_path: Path) -> str:
    if not glossary_path.exists():
        return ""
    text = glossary_path.read_text(encoding="utf-8")
    # Trim to a reasonable size for the system prompt
    lines = [ln for ln in text.splitlines() if ln.startswith("|")]
    return "\n".join(lines[:300])


def translate_one(client: anthropic.Anthropic, model: str, glossary: str, en_text: str) -> str:
    glossary_block = f"\n\nUse this glossary for UI term consistency:\n{glossary}\n" if glossary else ""
    msg = client.messages.create(
        model=model,
        max_tokens=8192,
        system=SYSTEM_PROMPT + glossary_block,
        messages=[{"role": "user", "content": en_text}],
    )
    return "".join(block.text for block in msg.content if block.type == "text")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, type=Path, help="EN markdown source dir")
    ap.add_argument("--dst", required=True, type=Path, help="ZH markdown output dir")
    ap.add_argument("--model", default="claude-opus-4-6")
    ap.add_argument("--glossary", type=Path, default=None)
    ap.add_argument("--force", action="store_true", help="Re-translate even if hash matches")
    args = ap.parse_args()

    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("ERROR: ANTHROPIC_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    client = anthropic.Anthropic()
    glossary = load_glossary(args.glossary) if args.glossary else ""

    # Cache lives next to the docs/ root (parent of src/)
    cache_root = args.src.parent.parent
    cache = load_cache(cache_root)

    en_files = sorted(args.src.glob("*.md"))
    args.dst.mkdir(parents=True, exist_ok=True)

    translated = 0
    skipped = 0
    for en_path in en_files:
        if en_path.name in SKIP:
            skipped += 1
            continue
        h = file_hash(en_path)
        cache_key = en_path.name
        if not args.force and cache.get(cache_key) == h and (args.dst / en_path.name).exists():
            skipped += 1
            continue

        print(f"Translating {en_path.name}…", flush=True)
        en_text = en_path.read_text(encoding="utf-8")
        try:
            zh_text = translate_one(client, args.model, glossary, en_text)
        except Exception as e:
            print(f"  FAILED: {e}", file=sys.stderr)
            continue
        (args.dst / en_path.name).write_text(zh_text, encoding="utf-8")
        cache[cache_key] = h
        translated += 1
        save_cache(cache_root, cache)  # save after each so partial runs are resumable

    print(f"Done. Translated: {translated}, skipped (unchanged or auto-gen): {skipped}")


if __name__ == "__main__":
    main()
